# This file is used to define the substitutions for the prod environment
# on the cli when we use the flag -e prod this file is used to define the environment variables
# and the secrets to use for the prod environment
prod:
  env: prod
  catalog: acme_edw_prod
  landing_volume: /Volumes/{catalog}/{raw_schema}/incoming_volume
  migration_schema: edw_old
  raw_schema: edw_raw
  bronze_schema: edw_bronze
  silver_schema: edw_silver
  gold_schema: edw_gold
  modelled_schema: edw_gold
  
secrets:
  default_scope: prod_secrets
  scopes:
    database: prod_db_secrets